### ISSUE TITLE
Running Script produces no output and does nothing.

### ISSUE THREAD

**Issue by GinnyScanny** [ivan-sincek/php-ransomware#2]
Hello, I've tested the script on 2 servers and it only runs without doing nothing.
I deleted the /header killswitch and uncommented the ->run call.
but still the page renders white, there is no error_log and error_reporting is 1.
Please help.

Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0ubuntu0.16.04.12, Copyright (c) 1999-2017, by Zend Technologies

nginx version: nginx/1.10.3 (Ubuntu)

**Comment by ivan-sincek** [comment]
Hi,

Sorry for the late reply.

On web servers other than XAMPP (Apache) you must load OpenSSL and Multibyte String libraries.

In XAMPP it is as simple as uncommenting the following in the "php.ini" file:
```
extension=php_openssl.dll
extension=mbstring
```

As I am not an expert in configuring NGNIX please search the Internet for a solution. Thank you. I hope I helped at least a little bit.

Best regards,
Ivan.

**Comment by ivan-sincek** [comment]
I am closing this issue.
