### ISSUE TITLE
How To Get the Decryption Key?

### ISSUE THREAD

**Issue by auwebsites** [ivan-sincek/php-ransomware#3]

**Comment by ivan-sincek** [comment]
Hi,

If you have the generated decryption file, the key should be within the file at `<input type="hidden" value="<recovery/>" placeholder="b64-recovery">`, and this is only if you have the latest update. Then, use [www.base64decode.org](https://www.base64decode.org) to decode the key.

If you lost your generated decryption file, you cannot do anything. That is why I strongly advise the use of virtual machines, and data backup.

Please use the open source malware responsibly. Thank you.

Best regards,
Ivan.

**Comment by auwebsites** [comment]
Thank you.
